### ISSUE TITLE
docs: You have mentioned that Getx have Android Studio Plugin but unfortunately it is not maintained. 

### ISSUE THREAD

**Issue by hayatbangash55** [chornthorn/getx-docs#18]
**Description**
![1](https://user-images.githubusercontent.com/78781155/220583644-78bd4cac-1113-487e-bd36-4485a6791468.PNG)

**In addition, to further increase your productivity, we have the [extension to VSCode](https://marketplace.visualstudio.com/items?itemName=get-snippets.get-snippets) and the [extension to Android Studio/Intellij](https://plugins.jetbrains.com/plugin/14975-getx-snippets)**

**Requirements**

Please remove it from the documentation or maintain the plugin because it's misleading.

**Comment by chornthorn** [comment]
This repository is only for GetX docs.

**Comment by hayatbangash55** [comment]
ok
